"""init incident models

Revision ID: dd2e9efc10e4
Revises: 
Create Date: 2026-03-15 14:40:57.524216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd2e9efc10e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_cases',
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('header', sa.Text(), nullable=True),
    sa.Column('failure_text', sa.Text(), nullable=False),
    sa.Column('impact_text', sa.Text(), nullable=True),
    sa.Column('solution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pending_rca', sa.Boolean(), nullable=False),
    sa.Column('raw_sms', sa.Text(), nullable=True),
    sa.Column('probable_cause_text', sa.Text(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('component_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('components_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('services_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('teams_involved', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tickets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enrichment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('incident_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.String(length=16), nullable=True),
    sa.Column('event_text', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('action_detected', sa.String(length=128), nullable=True),
    sa.Column('observation_detected', sa.String(length=128), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['incident_cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('troubleshooting_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('action_role', sa.String(length=64), nullable=True),
    sa.Column('target_component', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('was_effective', sa.Boolean(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['incident_cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('troubleshooting_actions')
    op.drop_table('incident_events')
    op.drop_table('incident_cases')
    # ### end Alembic commands ###
